**Import numpy library**

In [ ]:
import numpy as np
prime_array=np.array([2,3,5,7])
print(prime_array)
print(type(prime_array))

[2 3 5 7]
<class 'numpy.ndarray'>


In [ ]:
#Create 2 dimensional array
an_a=np.array([[2,3,4],[5,6,7],[8,9,10]])
print(an_a)
print(an_a.shape)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
(3, 3)


In [ ]:
a_t=np.array([[[1,2],[3,4]]
              ,[[5,6],[7,8]],
              [[9,10],[11,12]],
              [[13,14],[15,16]]])
print(a_t)
print(a_t.shape)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]
(4, 2, 2)


ARRAY SHAPE

In [ ]:
a_r=np.array([[[[1,2],[3,4]],
               [[5,6],[7,8]]]])
print(a_r)
print(a_r.shape)

[[[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]]
(1, 2, 2, 2)


ARRAY DIMENSION

In [ ]:
a_r=np.array([[[[1,2],[3,4]],
               [[5,6],[7,8]]]])
print(a_r.ndim)

4


ARRAY SIZE

In [ ]:
a_r=np.array([[[[1,2],[3,4]],
               [[5,6],[7,8]]]])
print(a_r.size)

8


ARRAY DATA TYPE

In [ ]:
a_r=np.array([[[[1,2],[3,4]],
               [[5,6],[7,8]]]])
print(a_r.dtype)

int64


ASTYPE

In [ ]:
a_r=np.array([[[[1,2],[3,4]],
               [[5,6],[7,8]]]])
k=a_r.astype('float64')
print(k)
print(k.dtype)

[[[[1. 2.]
   [3. 4.]]

  [[5. 6.]
   [7. 8.]]]]
float64


INITIALIZE ARRAY WITH ZEROES


In [ ]:
zero_arr=np.zeros((3,3), dtype=int)
zero_arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

INITIALIZE WITH ONES

In [ ]:
one_arr=np.ones((4,3),dtype=int)

RANGE OF NUMERICAL VALUES

In [ ]:
k=np.arange(5)
l=np.arange(10,50,5)
print(l)

[10 15 20 25 30 35 40 45]


In [ ]:
s=np.linspace(10,20,9, endpoint=True, dtype=int)
print(s)

[10 11 12 13 15 16 17 18 20]


RANDOM NUMBERS GENERATED

In [ ]:
random_arr=np.random.random((4,3))
random_arr

array([[0.93086265, 0.90039796, 0.75143455],
       [0.78587596, 0.38008022, 0.34314464],
       [0.4442104 , 0.60310842, 0.61921931],
       [0.10390099, 0.94129577, 0.9454995 ]])

RAND INT ONLY INTEGERS WITH END POINT NOT INCLUDED

In [ ]:
rand_int=np.random.randint(0,5,size=(2,3,4))
rand_int

array([[[2, 3, 2, 1],
        [1, 0, 3, 4],
        [4, 4, 2, 2]],

       [[3, 1, 0, 3],
        [2, 1, 0, 3],
        [2, 2, 1, 3]]])

ASARRAY:CHANGE TO ARRAY

In [ ]:
lis_1=[1,2,3,4]
cor_ar=np.asarray(lis_1)

INDEXING AND SLICING

In [ ]:
#FOR 1-D SAME AS LIST
k=np.random.randint((3,3,3))
k

array([1, 2, 2])

In [ ]:
a = np.array([[[1,2],[3,4],[5,6]],
             [[7,8],[9,10],[11,12]],
             [[13,14],[15,16],[17,18]]])
print(a[0:2,1:,1:])

[[[ 4]
  [ 6]]

 [[10]
  [12]]]


In [ ]:
b=a[0:2,1:,1:]
print(b.shape)
print(b)

(2, 2, 1)
[[[ 4]
  [ 6]]

 [[10]
  [12]]]


In [ ]:
dp=np.full((3,2),7)
print(dp)

[[7 7]
 [7 7]
 [7 7]]
